version: "2.4"

services:
  database:
    extends:
      file: ./services/database.yml
      service: database

volumes:
  ha-postgres-vol:
    external: false

networks:
  ha-local:
    external: false
